services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-dbs.sql:/docker-entrypoint-initdb.d/init-dbs.sql
    networks:
      - micro_network

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - micro_network

# Flask User service
  users-service:
    build: ./users-service
    container_name: flask_users_service
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=${USERS_DB_URL}
    depends_on:
      - db
      - rabbitmq
    networks:
      - micro_network

# FastAPI Products service
  products-service:
    build: ./products-service
    container_name: fastapi_products_service
    ports:
      - "5002:5002"
    environment:
      - DATABASE_URL=${PRODUCTS_DB_URL}
    depends_on:
      - db
      - rabbitmq
    networks:
      - micro_network

  orders-service:
    build: ./orders-service
    container_name: fastapi_orders_service
    ports:
      - "5003:5003"
    environment:
      - USER_SERVICE_URL=http://flask_users_service:5001
    depends_on:
      - db
      - rabbitmq
      - users-service
      - products-service
    networks:
      - micro_network

volumes:
  postgres_data:

networks:
  micro_network:
    driver: bridge